---
title: "Objektorienteret"
teaching: 0
exercises: 0
questions:
- "Key question (FIXME)"
objectives:
- "First learning objective. (FIXME)"
keypoints:
- "First key point. Brief Answer to questions. (FIXME)"
---

Hvorfor?

class -  The template

Object - 

Encapsulation

Inheritance

Polymorphism

Der er flere måder at bygge objekter i R. 

R6.

```{r}
library(R6)
library(ggplot2)

GaussianSimulator <- R6Class("GaussianSimulatorClass",
                            public = list(
                              mu = NA,
                              sigma = NA,
                              n_sample = NA,
                              sample = NA,
                              
                              initialize = function(mu, sigma, n_sample){
                                # Object Initiator
                                # Args
                                #   mu: mean of the distribution
                                #   sigma: std. ev. of the distribution
                                #   n_sample: size of the sample
                                
                                self$mu <- mu
                                self$sigma <- sigma
                                self$n_sample <- n_sample
                              },
                              
                              get_sample_size = function(){
                                # getter method
                                
                                return(self$n_sample)
                              },
                              
                              set_sample_size = function(size){
                                # setter method
                                
                                self$n_sample = size
                              },
                              
                              generate_sample = function(){
                                # generates the random sample
                                
                                self$sample <- rnorm(self$n_sample, self$mu, self$sigma)
                                return(self$sample)
                              },
                              
                              compute_stats = function(){
                                # computes basic statistics of the sample
                                
                                r <- list(sample.mean = mean(self$sample),
                                          sample.sd = sd(self$sample))
                                return(r)
                              },
                              
                              plot_histogram = function(binwidth){
                                p <- qplot(self$sample, geom = "histogram",
                                           breaks = seq(130, 200, binwidth),
                                           colour = I("black"), fill = I("white"),
                                           xlab = "X", ylab = "Count") 
                                return(p)
                              }
                            ))
```


```{r}
sm <- GaussianSimulator$new(mu=165, sigma=6.6, n_sample=1000)
# creates a new object of the class GaussianSimulator

r <- sm$generate_sample()
# generates a random sample
basic.stats <- sm$compute_stats()
# computes basic statistics of the sample
p <- sm$plot_histogram(binwidth = 2)
# creates the histogram
p
```



{% include links.md %}